// src/js/pages/terms.js
export function renderTermsPage(state, _supabase, navigateTo) {
    const page = document.getElementById('page-terms');
    if (!page) return;

    page.innerHTML = `
        <style>
            .policy-container {
                max-width: 800px;
                margin: 0 auto;
                padding: 40px 20px;
                color: var(--text, #e8e8f0);
            }
            .policy-container h1 {
                font-size: 28px;
                color: var(--gold, #d4a000);
                margin-bottom: 8px;
            }
            .policy-container .last-updated {
                color: var(--text3, #666);
                font-size: 13px;
                margin-bottom: 32px;
            }
            .policy-container h2 {
                font-size: 18px;
                color: var(--gold, #d4a000);
                margin-top: 28px;
                margin-bottom: 12px;
            }
            .policy-container p {
                font-size: 14px;
                line-height: 1.7;
                color: var(--text2, #aaa);
                margin-bottom: 12px;
            }
            .policy-container ul {
                padding-left: 24px;
                margin-bottom: 16px;
            }
            .policy-container li {
                font-size: 14px;
                line-height: 1.7;
                color: var(--text2, #aaa);
                margin-bottom: 6px;
            }
            .policy-container .back-link {
                color: var(--gold, #d4a000);
                text-decoration: none;
                display: inline-block;
                margin-bottom: 24px;
                font-size: 14px;
            }
            .policy-container .back-link:hover {
                text-decoration: underline;
            }
            .policy-divider {
                border: none;
                border-top: 1px solid rgba(255, 255, 255, 0.06);
                margin: 24px 0;
            }
            @media (max-width: 600px) {
                .policy-container { padding: 24px 16px; }
                .policy-container h1 { font-size: 22px; }
                .policy-container h2 { font-size: 16px; }
            }
        </style>

        <div class="policy-container">
            <a href="#" class="back-link" id="backLink">← Back</a>
            <h1>Terms of Service</h1>
            <p class="last-updated">Last updated: June 2026</p>

            <p>Welcome to CheatCode. By using our platform, you agree to these Terms of Service. Please read them carefully.</p>

            <hr class="policy-divider">

            <h2>1. Acceptance of Terms</h2>
            <p>By creating an account or using CheatCode, you agree to be bound by these terms. If you do not agree, please do not use the platform.</p>

            <h2>2. Account & Subscription</h2>
            <ul>
                <li><strong>Free Trial:</strong> New users receive a 7-day free trial with limited questions per day.</li>
                <li><strong>Pro Access:</strong> A one-time payment of $7.99 grants unlimited access to all features.</li>
                <li><strong>No Recurring Fees:</strong> There are no monthly or yearly subscription fees.</li>
            </ul>

            <h2>3. User Responsibilities</h2>
            <ul>
                <li>You are responsible for the content you upload and share</li>
                <li>You may not use CheatCode for illegal or harmful purposes</li>
                <li>You must keep your account credentials secure</li>
            </ul>

            <h2>4. Intellectual Property</h2>
            <ul>
                <li><strong>Your Content:</strong> You retain ownership of all materials you upload</li>
                <li><strong>AI Outputs:</strong> Responses generated by the AI are for personal study use only</li>
                <li><strong>Our Platform:</strong> The platform design and code are our intellectual property</li>
            </ul>

            <h2>5. Payment & Refunds</h2>
            <ul>
                <li>Payments are processed securely through Fapshi</li>
                <li>Pro Access is a one-time, non-refundable payment</li>
                <li>Activation codes are valid for one-time use only</li>
            </ul>

            <h2>6. Limitation of Liability</h2>
            <p>CheatCode is provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of our platform.</p>

            <h2>7. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms or engage in misuse of the platform.</p>

            <h2>8. Governing Law</h2>
            <p>These terms are governed by the laws of the Republic of Cameroon. Any disputes shall be resolved in the courts of Cameroon.</p>

            <h2>9. Changes to Terms</h2>
            <p>We may update these terms from time to time. We will notify you of any significant changes.</p>

            <h2>10. Contact</h2>
            <p>If you have questions about these terms, please contact us at: <a href="mailto:support@cheatcode.app" style="color:var(--gold);">support@cheatcode.app</a></p>
        </div>
    `;

    document.getElementById('backLink')?.addEventListener('click', (e) => {
        e.preventDefault();
        navigateTo('dashboard');
    });
}